# This is a basic workflow to help you get started with Actions

name: Newman Run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create dir for reports
      - run: mkdir testArtifacts

      - name: Install Newman
      - run: npm install -g newman
      - run: npm i newman-reporter-htmlextra

      - name: Run Test
      - run: newman run Serverest.dev.postman_collection.json -e ServeRest.postman_environment.json -r cli,htmlextra

      - name: Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Reports
          path: newman
